env: dev
configValues: |

  providerConfigName: commercial-dev-config
  billingAccountId: 00CD44-0B2D32-2F1E33
  namespace: commercial-dev

  project:
  - name: proj-sbawane-sbox
    projectId: proj-sbawane-sbox-torg-dev
    autoCreateNetwork: false
    folderName: fldr-commercial-dev
    projectName: proj-sbawane-sbox
    #enableExternalName: true
    projectLabels:
      business_unit: sbox
      platform: na
      service: sbox
      application: sbox
      environment: dev
      product: sbox
      owner_email: shivam-dot-bawane-at-vonage-dot-com
      support_group_email: cloud-ops-at-vonage-dot-com
      support_group_slack: cloudops
      opsgenie_contact: cloudops
      department: cloudops
      cost_center: 765
      vsa_uspr_classified: yes
      vsa_pe_classified: yes
      vsa_noc_classified: yes
      vsa_dci_classified: yes
      vsa_sc_classified: yes
      compliancy_code: unknown
      ipsanction_policy: true
      ca_scope_1: global
      ca_scope_2: us-south1
      ca_scope: na
      priority: true

  projectServices:
  - name: proj-sbawane-sbox-enable-apis
    disableOnDestroy: false
    disableDependentServices: false
    projectName: proj-sbawane-sbox
    services:
    - billingbudgets.googleapis.com
    - firewallinsights.googleapis.com
    - networkmanagement.googleapis.com
    - networksecurity.googleapis.com

  notificationChannels:
  - name: cloudops-team-sbawane-torg-dev
    emailAddress: shivam.bawane@vonage.com
    projectId: proj-sbawane-sbox-torg-dev

  projectIAM:
  - name: proj-sbawane-sbox-roles-guru
    userEmail: guruprasad.reddy@vonage.com
    roles:
    - roleName: "compute-security-admin"
      role: "roles/compute.securityAdmin"
    - roleName: "compute-network-admin"
      role: "roles/compute.networkAdmin"
    - roleName: "editor"
      role: "roles/editor"
      resourceDeletionPolicy: Delete
    projId: proj-sbawane-sbox-torg-dev
  
  - name: proj-sbawane-sbox-roles-aman
    userEmail: aman.jangid@vonage.com
    roles:
    - roleName: "compute-security-admin"
      role: "roles/compute.securityAdmin"
    - roleName: "compute-network-admin"
      role: "roles/compute.networkAdmin"
    - roleName: "editor"
      role: "roles/editor"
      resourceDeletionPolicy: Delete
    projId: proj-sbawane-sbox-torg-dev
  
  # networks:
  #   - vpcName: vpc-standalone-sbawane-sbox
  #     description: VPC for sbawane sbox project
  #     project: proj-sbawane-sbox
  #     autoCreateSubnetworks: false
  #     routingMode: GLOBAL
  #     labels:
  #       network-name: vpc-standalone-sbawane-sbox

  # subnets:
  #   - subnetName: subnet-sbox-priv-useast1-dev-01
  #     networkSelector:
  #       matchLabels:
  #         network-name: vpc-standalone-sbawane-sbox
  #     ipCidrRange: 10.198.0.0/24
  #     description: IP Subnet for sbawane sbox
  #     project: proj-sbawane-sbox
  #     privateIpGoogleAccess: true
  #     logConfig:
  #     - aggregationInterval: INTERVAL_1_MIN
  #     region: us-east1
  #     labels:
  #       subnet-name: subnet-sbox-priv-useast1-dev-01