env: dev
configValues: |

  providerConfigName: commercial-dev-config
  billingAccountId: 00CD44-0B2D32-2F1E33
  namespace: commercial-dev

  project:
  - name: proj-nsarabu-sbox
    projectId: proj-nsarabu-sbox-torg-dev
    autoCreateNetwork: false
    folderName: fldr-commercial-dev
    projectName: proj-nsarabu-sbox
    #enableExternalName: true
    projectLabels:
      business_unit: sbox
      platform: na
      service: sbox
      application: sbox
      environment: dev
      product: sbox
      owner_email: naveen-dot-sarabu-at-vonage-dot-com
      support_group_email: cloud-ops-at-vonage-dot-com
      support_group_slack: cloudops
      opsgenie_contact: cloudops
      department: cloudops
      cost_center: 765
      vsa_uspr_classified: yes
      vsa_pe_classified: yes
      vsa_noc_classified: yes
      vsa_dci_classified: yes
      vsa_sc_classified: yes
      compliancy_code: unknown

  projectServices:
  - name: proj-nsarabu-sbox-enable-apis
    disableOnDestroy: false
    disableDependentServices: false
    projectName: proj-nsarabu-sbox
    services:
    - billingbudgets.googleapis.com
    - firewallinsights.googleapis.com
    - networkmanagement.googleapis.com

  notificationChannels:
  - name: cloudops-team-nsarabu-torg-dev
    emailAddress: naveen.sarabu@vonage.com
    projectId: proj-nsarabu-sbox-torg-dev
  
  
  # networks:
  #   - vpcName: vpc-standalone-nsarabu-sbox
  #     description: VPC for nsarabu sbox project
  #     project: proj-nsarabu-sbox
  #     autoCreateSubnetworks: false
  #     routingMode: GLOBAL
  #     labels:
  #       network-name: vpc-standalone-nsarabu-sbox

  # subnets:
  #   - subnetName: subnet-sbox-priv-useast1-dev-01
  #     networkSelector:
  #       matchLabels:
  #         network-name: vpc-standalone-nsarabu-sbox
  #     ipCidrRange: 10.198.0.0/24
  #     description: IP Subnet for nsarabu sbox
  #     project: proj-nsarabu-sbox
  #     privateIpGoogleAccess: true
  #     logConfig:
  #     - aggregationInterval: INTERVAL_1_MIN
  #     region: us-east1
  #     labels:
  #       subnet-name: subnet-sbox-priv-useast1-dev-01

  