name: Repo Restructuring on Commit

on:
  push:
    branches: ['main']
    paths: ['fldr-cf.yaml']

permissions:
  contents: write
  pull-requests: write

jobs:
  automate_job:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyyaml

      - name: Update Directory Structure
        run: python repo-structure.py

      - name: Update fldr-cf.yaml
        run: python env-setup.py fldr-cf

      - name: Check for changes
        id: changes
        run: |
          git add .
          if git diff --cached --quiet; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "No changes detected"
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "Changes detected"
            git status
          fi

      - name: Create Pull Request
        if: steps.changes.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Automated PR: Repo Structure Updated (Run #${{ github.run_number }})"
          body: |
            This PR contains automated restructuring based on fldr-cf.yaml.
            
            **Changes made:**
            - Updated directory structure via repo-structure.py
            - Updated fldr-cf.yaml via env-setup.py
            
            Auto-generated on: ${{ github.event.head_commit.timestamp }}
          base: main
          branch: auto/pr-branch-${{ github.run_number }}
          commit-message: "Automated repo-restructure from fldr-cf.yaml (Run #${{ github.run_number }})"
          delete-branch: true

      - name: PR Creation Result
        if: steps.changes.outputs.has_changes == 'true'
        run: |
          echo "PR should have been created. Check the Actions logs above for any errors."
          echo "If PR wasn't created, check:"
          echo "1. Repository permissions"
          echo "2. GITHUB_TOKEN permissions"
          echo "3. Branch protection rules"
