name: Repo - Restructuring on commit
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - 'fldr-cf.yaml'

jobs:
  automate_job:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pyyaml
    - name: Update Directory Structure
      run: python repo-structure.py
    - name: Update fldr-cf.yaml
      run: python env-setup.py fldr-cf
    - name: Commit Changes
      run: |
        git config --global user.name 'amanmuleva'
        git config --global user.email 'aman.muleva@vonage.com'
        git add .
        git commit -m "Automated repo-restructure"
        git push origin main
