name: Repo - Restructuring on commit
on:
  push:
    branches: ['main']
    paths: ['fldr-cf.yaml']
permissions:
  contents: write
  pull-requests: write

jobs:
  automate_job:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pyyaml
    - name: Update Directory Structure
      run: python repo-structure.py
    - name: Update fldr-cf.yaml
      run: python env-setup.py fldr-cf
    - name: Create PR Branch
      run: |
        git config --global user.name 'amanmuleva'
        git config --global user.email 'aman.muleva@vonage.com'
        git checkout -b auto/pr-branch-1
        git add .
        git commit -m "Automated repo-restructure"
        git push origin auto/pr-branch-1
    - name: Create Pull Request
      env: 
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        BRANCH_NAME="auto/pr-branch-1"
        gh pr create \
          --title "Automated PR - Repo Structure Updated" \
          --body "This PR contains automatically restructured directory" \
          --head auto/pr-branch-1 \
          --base main
